export const CELL_SIZE = 15;
export const GRID_SIZE = 50;
export const LEGEND_ORDER = [
  "STRUCTURE_SPAWN",
  "STRUCTURE_EXTENSION",
  "STRUCTURE_CONTAINER",
  "STRUCTURE_STORAGE",
  "STRUCTURE_LINK",
  "STRUCTURE_ROAD",
  "STRUCTURE_TOWER",
  "STRUCTURE_TERMINAL",
  "STRUCTURE_LAB",
  "STRUCTURE_EXTRACTOR",
  "STRUCTURE_FACTORY",
  "STRUCTURE_WALL",
  "STRUCTURE_RAMPART",
];
