export const CREEP_BODY = {
  PIONEER: [WORK, CARRY, MOVE, CARRY, MOVE],
  HARVESTER: [WORK, CARRY, MOVE, WORK, WORK, WORK, WORK],
  CARRIER: [
    MOVE,
    CARRY,
    CARRY,
    MOVE,
    CARRY,
    CARRY,
    MOVE,
    CARRY,
    CARRY,
    MOVE,
    CARRY,
    CARRY,
  ],
  DEFENDER: [
    TOUGH,
    ATTACK,
    MOVE,
    MOVE,
    TOUGH,
    ATTACK,
    MOVE,
    MOVE,
    TOUGH,
    ATTACK,
    MOVE,
    MOVE,
  ],
  WORKER: [WORK, CARRY, MOVE, WORK, CARRY, MOVE, WORK, CARRY, MOVE],
} satisfies Record<string, BodyPartConstant[]>;
