export const CREEP_BODY = {
  PIONEER: [WORK, CARRY, MOVE, CARRY, MOVE],
  HARVESTER: [WORK, CARRY, MOVE, WORK, WORK, CARRY, WORK, WORK, MOVE, WORK],
  UPGRADER: [
    WORK,
    CARRY,
    MOVE,
    WORK,
    WORK,
    WORK,
    WORK,
    MOVE,
    WORK,
    WORK,
    WORK,
    WORK,
  ],
  CARRIER: [
    MOVE,
    CARRY,
    MOVE,
    CARRY,
    MOVE,
    CARRY,
    MOVE,
    CARRY,
    MOVE,
    CARRY,
    MOVE,
    CARRY,
    MOVE,
    CARRY,
    MOVE,
    CARRY,
  ],
  DEFENDER: [
    TOUGH,
    ATTACK,
    MOVE,
    MOVE,
    TOUGH,
    ATTACK,
    MOVE,
    MOVE,
    TOUGH,
    ATTACK,
    MOVE,
    MOVE,
  ],
  WORKER: [WORK, CARRY, MOVE, WORK, CARRY, WORK, MOVE, WORK, CARRY, MOVE],
} satisfies Record<string, BodyPartConstant[]>;
